name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: yarn install
        
      - name: Set environment variables
        run: |
          mkdir env
          touch env/.env.local
          echo "GITHUB_PRIVATE_KEY=${{secrets.GH_PRIVATE_KEY}}" >> env/.env.local
          echo "GITHUB_APP_IDENTIFIER=${{secrets.GH_APP_IDENTIFIER}}" >> env/.env.local
          echo "GITHUB_WEBHOOK_SECRET=${{secrets.GH_WEBHOOK_SECRET}}" >> env/.env.local
          echo "GITHUB_CLIENT_SECRET=${{secrets.GH_CLIENT_SECRET}}" >> env/.env.local
          echo "AWS_S3_SECRET_KEY=${{secrets.AWS_S3_SECRET_KEY}}" >> env/.env.local
          echo "AWS_S3_ACCESS_KEY=${{secrets.AWS_S3_ACCESS_KEY}}" >> env/.env.local
          echo "PRISMA_DB_URL=${{secrets.PRISMA_DB_URL}}" >> env/.env.local
          echo "PUBLIC_REPO_PATH=${{secrets.PUBLIC_REPO_PATH}}" >> env/.env.local
          echo "PUBLIC_GITHUB_CLIENT_ID=${{secrets.PUBLIC_GITHUB_CLIENT_ID}}" >> env/.env.local
          echo "PUBLIC_GITHUB_REDIRECT_URI=${{secrets.PUBLIC_GITHUB_REDIRECT_URI}}" >> env/.env.local
          echo "PUBLIC_GITHUB_ACCESS_URL=${{secrets.PUBLIC_GITHUB_ACCESS_URL}}" >> env/.env.local
      
      - name: Build Svelte app
        run: yarn build
      
      - name: Deploy to Linode
        uses: appleboy/ssh-action@master
        with:
          host: 170.187.251.166
          username: adithya29
          key: ${{ secrets.LINODE_PRIVATE_KEY }}
          script: |
            cd /home
            rm -rf *
            cp -R /home/solana-devops/public/* .
