name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: yarn install
      
      - name: Build Svelte app
        run: yarn build
      
      - name: Deploy to Linode
        uses: appleboy/ssh-action@master
        with:
          host: 170.187.251.166
          username: adithya29
          key: ${{ secrets.LINODE_PRIVATE_KEY }}
          script: |
            cd /home
            rm -rf *
            cp -R /home/solana-devops/public/* .
